config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:create, :new] do
    resources :comments, only: [:create, :new]
    resources :likes, only: [:create, :destroy]
  end  
  
  resources :likes, only: [:create, :destroy], param: :likeable_id


  devise_for :users
  root "site#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable
  # after_create_commit { broadcast_append_to "posts" }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
  end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :likeable, polymorphic: true
    validates :user_id, uniqueness: { scope: [:likeable_id, :likeable_type] }
end     

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable
  # after_create_commit { broadcast_append_to "posts" }

  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true

  has_many :comments 
  has_many :posts
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_params, if: :devise_controller?
        
    protected
        def configure_permitted_params
            devise_parameter_sanitizer.permit(:sign_up, keys:  [:username])
        end    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post
    def new
    end    

    def create
        comment = Comment.new(comment_params)
        comment.post = @post
        comment.user = current_user
        if comment.save
          # Return a Turbo Stream response that appends the comment to the correct post
          render turbo_stream: turbo_stream.append("comments_for_post_#{@post.id}", partial: "comments/comment", locals: { comment: comment })
        else
          render :new, status: :unprocessable_entity
        end
      end   

    private
        def set_post
            @post = Post.find(params[:post_id])
        end    
        
        def comment_params 
            params.require(:comment).permit(:body)
        end   

    end

app/controllers/likes_controller.rb
class LikesController < ApplicationController  
  def create
    @like = current_user.likes.new(like_params)
    @like.liked = true
    if !@like.save
      flash[notice:] = @like.errors.full_messages.to_sentence
    end
    redirect_to root_path
  end

  def destroy  
    @like = current_user.likes.find_by(likeable_id: params[:likeable_id])
    
    if @like
      likeable = @like.likeable
      @like.destroy
      redirect_to root_path, notice: 'Like removed.'
    else
      redirect_to root_path, alert: 'Like not found.'
    end
  end

  private
    def like_params
      params.require(:like).permit(:likeable_id, :likeable_type)
    end

  
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end  

  def new
    @post= Post.new
  end

  def create
    
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.valid?
      @post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end    
  end

  private
    def post_params
      params.require(:post).permit(:body)
    end  
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    def index
        @posts = Post.all
    end   
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/comments/_comment.html.erb
<div id= "<%= dom_id comment %>">
    <span class="comment-author"> 
        <%= comment.user.username %> 
    </span>
        <%= comment.body %>

    <%= render "likes/like", likeable: comment %>
    
</div>

app/views/comments/_form.html.erb
<%= turbo_frame_tag "comment-form" do %>
  <%= form_with model: Comment.new, url: post_comments_path(post), class: "comment-form" do |f| %>
    <%= f.text_field :body %>
    <%= f.submit :post %>
  <% end %>
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css"> %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="nav"> 
        <% if user_signed_in? %>
        <div id="home">
          <%= link_to "Home", root_path %>
        </div>  
        <div id="access">
          <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete}  %>
        </div>  
        <% else %>
          <%= link_to "Sign In", new_user_session_path  %>
        <% end %>
    </div>
    <div class="main">
    <% if user_signed_in? %>
        <%= turbo_frame_tag "post-form" do %>
          <%= link_to "New post", new_post_path %>
        <% end %>
      <% end%>  
      <%= yield %>
    </div>  
  </body>
</html>

app/views/likes/_like.html.erb
<%= turbo_frame_tag "#{likeable.class.name.downcase}-likes-#{likeable.id}" do %>
    <%# DISLIKE BUTTON %>
  <% if current_user && (like = Like.find_by(user_id: current_user.id, likeable: likeable, liked: true)) %>
    <%= button_to "", like_path(likeable_id: like.likeable_id), class: "post-actions-unlike", method: :delete %>
  <% else %>
    <%# LIKE BUTTON %>
    <%= button_to likes_path(likeable), class: "post-actions-like", method: :post do %>
      <%= hidden_field_tag "like[likeable_id]", likeable.id %>
      <%= hidden_field_tag "like[likeable_type]", likeable.class.name %>
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.html.erb
<%= turbo_frame_tag "post-likes" do %>
    <%= button_to "", post_likes_path(@post), class: "post-actions-unlike" %>
<% end %>
 
   

app/views/likes/destroy.html.erb
<%= turbo_frame_tag "post-likes" do %>
    <%= button_to "", post_like_path(@post), class: "post-actions-like", method: :delete %>
<% end %>

app/views/posts/_post.html.erb
<div id= "<%= dom_id post %>">
    <div class= "post-author">
        <div class= "avatar avatar-<%= rand(1..27) %>"></div>
        <div><%= post.user.username %></div>
    </div>
    <div class= "post-body">
        <span> <%= post.body %></span>
    </div> 
    
    <%= render "likes/like", likeable: post %>
    
    <%= render "comments/form", post: post %>
    
    <div id="comments">
        <%= turbo_frame_tag "comments_for_post_#{post.id}" do %>
            <%= render post.comments %>
        <% end %>
    </div>
</div>    

app/views/posts/new.html.erb
<%= turbo_frame_tag "post-form" do %>
    <%= form_with model: @post do |f| %>
        <%= f.text_field :body %>
        <%= f.submit :send %>
    <% end %>
<% end %>    

app/views/posts/show.html.erb
<%= render @post %>
<%= render "post/comments", post: @post %>





  

app/views/site/index.html.erb
<%= turbo_stream_from "posts" %>
    <div id= "posts">
        <%= render @posts %>
    </div>